language: node_js
node_js:
- '6'
script:
- npm run build
cache:
  directories:
    - node_modules
deploy:
  provider: pages
  edge:
    branch: v1.8.47
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master