language: node_js
node_js:
- '6'
script:
- npm run build
- npm run postBuild
cache:
  directories:
    - node_modules
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: dist
  on:
    branch: master